Repository garden-io/garden, pull requests merged in 2019-07, with the labels that each got.

#939 fix(task-graph): emit and handle taskCancelled events
  dashboard/src/components/graph/graph.scss
  dashboard/src/components/graph/index.tsx
  dashboard/src/context/events.tsx
  dashboard/src/styles/variables.ts
  garden-service/src/events.ts
  garden-service/src/task-graph.ts
  garden-service/test/unit/src/task-graph.ts
Labels: dashboard

#916 chore: added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#961 fix(k8s): ensure images built remotely are tagged before publishing
  garden-service/src/plugins/kubernetes/container/publish.ts
Labels: bug

#976 improvement: updated PATH to include all gcloud bin-s
  garden-service/gcloud.Dockerfile
Labels: enhancement
