Repository garden-io/garden, pull requests merged in 2023-06, with the labels that each got.

#4423 chore: disable analytics for WS server commands
  core/src/server/server.ts
Labels: 0.13.1

#4526 fix(dev): plugins outside of core package weren't available in dev+server
  core/src/cli/cli.ts
  core/src/cli/command-line.ts
  core/src/commands/dev.tsx
  core/src/commands/serve.ts
  core/src/server/commands.ts
  core/src/server/instance-manager.ts
  core/test/helpers.ts
  core/test/unit/src/cli/cli.ts
  core/test/unit/src/server/server.ts
Labels: priority:high, 0.13.1

#4569 0.12 back-port: fix(self-update): fix list of the latest available versions
  core/src/commands/self-update.ts
Labels: 0.12-maintenance

#4710 0.12-Backport: fix(template-strings): do not apply helper functions on unresolved string
  core/src/template-string/functions.ts
  core/test/unit/src/template-string.ts
Labels: 0.12-maintenance

#4722 fix(telemetry): do not throw in case of any runtime error
  core/src/analytics/analytics.ts
Labels: priority:critical, regression
