Repository garden-io/garden, pull requests merged in 2023-02, with the labels that each got.

#3639 0.13: implement container module conversion tests
  core/test/unit/src/plugins/container/container.ts
Labels: 0.13

#3676 fix: fix getDockerVersion helper
  core/src/plugins/container/helpers.ts
Labels: 0.13

#3682 chore(test): fix link.ts and unlink.ts test assertions
  core/test/unit/src/commands/link.ts
  core/test/unit/src/commands/unlink.ts
Labels: 0.13

#3704 refactor(cli): make -V instead of -v (lowercase) print Garden version
  core/src/cli/params.ts
  core/test/unit/src/cli/cli.ts
  docs/reference/commands.md
Labels: api-change, cli, 0.13

#3703 refactor(k8s): change default kaniko namespace to the project namespace
  core/src/plugins/kubernetes/config.ts
  core/src/plugins/kubernetes/container/build/kaniko.ts
  core/test/data/test-projects/container/garden.yml
  docs/k8s-plugins/advanced/in-cluster-building.md
  docs/reference/providers/kubernetes.md
  docs/reference/providers/local-kubernetes.md
  examples/kaniko/README.md
  examples/kaniko/garden.yml
Labels: api-change, 0.13

#3702 Remove watch mode flags
  core/src/commands/build.ts
  core/src/commands/delete.ts
  core/src/commands/deploy.ts
  core/src/commands/helpers.ts
  core/src/commands/publish.ts
  core/src/commands/run.ts
  core/src/commands/serve.ts
  core/src/commands/test.ts
  core/src/garden.ts
  core/src/graph/actions.ts
  core/src/outputs.ts
  core/src/process.ts
  core/src/router/router.ts
  core/src/server/client-router.ts
  core/src/tasks/base.ts
  core/src/tasks/helpers.ts
  core/src/tasks/resolve-provider.ts
  core/test/integ/src/plugins/hadolint/hadolint.ts
  core/test/integ/src/plugins/kubernetes/container/container.ts
  core/test/integ/src/plugins/kubernetes/container/deployment.ts
  core/test/integ/src/plugins/kubernetes/container/logs.ts
  core/test/integ/src/plugins/kubernetes/container/run.ts
  core/test/integ/src/plugins/kubernetes/dev-mode.ts
  core/test/integ/src/plugins/kubernetes/helm/common.ts
  core/test/integ/src/plugins/kubernetes/helm/run.ts
  core/test/integ/src/plugins/kubernetes/helm/test.ts
  core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
  core/test/integ/src/plugins/kubernetes/kubernetes-module/run.ts
  core/test/integ/src/plugins/kubernetes/kubernetes-module/test.ts
  core/test/integ/src/plugins/kubernetes/system.ts
  core/test/integ/src/plugins/kubernetes/util.ts
  core/test/integ/src/plugins/kubernetes/volume/configmap.ts
  core/test/integ/src/plugins/kubernetes/volume/persistentvolumeclaim.ts
  core/test/unit/src/build-staging/build-staging.ts
  core/test/unit/src/cli/helpers.ts
  core/test/unit/src/commands/deploy.ts
  core/test/unit/src/commands/run.ts
  core/test/unit/src/commands/test.ts
  core/test/unit/src/graph/solver.ts
  core/test/unit/src/plugins/exec/exec.ts
  core/test/unit/src/tasks/base.ts
  core/test/unit/src/tasks/deploy.ts
  core/test/unit/src/tasks/get-service-status.ts
  core/test/unit/src/tasks/helpers.ts
  core/test/unit/src/tasks/resolve-provider.ts
  core/test/unit/src/tasks/run.ts
  core/test/unit/src/tasks/test.ts
  docs/reference/commands.md
  docs/using-garden/tasks.md
  docs/using-garden/using-the-cli.md
  e2e/run-garden.ts
  e2e/test/pre-release.ts
  plugins/conftest-kubernetes/test/conftest-kubernetes.ts
  plugins/conftest/test/conftest.ts
  plugins/pulumi/commands.ts
  plugins/terraform/test/terraform.ts
Labels: api-change, 0.13, breaking-change

#3806 [0.13] feat(kubernetes): add sync helper commands
  core/src/constants.ts
  core/src/plugins/kubernetes/commands/sync.ts
  core/src/plugins/kubernetes/container/build/common.ts
  core/src/plugins/kubernetes/kubernetes.ts
  core/src/plugins/kubernetes/mutagen.ts
  core/src/plugins/kubernetes/sync.ts
  core/test/integ/src/plugins/kubernetes/commands/sync.ts
  core/test/integ/src/plugins/kubernetes/dev-mode.ts
Labels: 0.13
