Repository garden-io/garden, pull requests merged in 2023-05, with the labels that each got.

#4268 0.13 improvement(security): reference all images by sha256 from garden
  .circleci/config.yml
  cli/src/build-pkg.ts
  core/src/plugins/kubernetes/config.ts
  core/src/plugins/kubernetes/constants.ts
  core/src/plugins/kubernetes/container/build/buildkit.ts
  core/src/plugins/kubernetes/container/build/kaniko.ts
  core/src/plugins/kubernetes/jib-container.ts
  core/src/plugins/kubernetes/namespace.ts
  core/src/util/string.ts
  core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
  core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
  core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
  docs/guides/using-garden-in-ci.md
  docs/reference/providers/kubernetes.md
  docs/reference/providers/local-kubernetes.md
  images/buildkit/Dockerfile
  images/buildkit/garden.yml
  images/circleci-runner/Dockerfile
  images/docker-dind/Dockerfile
  images/docker-dind/garden.yml
  images/k8s-reverse-proxy/Dockerfile
  images/k8s-sync/Dockerfile
  images/skopeo/Dockerfile
  images/socat/Dockerfile
  images/socat/garden.yml
  static/kubernetes/system/default-backend/garden.yml
  static/kubernetes/system/ingress-controller/garden.yml
  static/kubernetes/system/nginx-kind/nginx-kind-old.garden.yml
  static/kubernetes/system/util/Chart.yaml
  static/kubernetes/system/util/templates/deployment.yaml
  static/kubernetes/system/util/values.yaml
Labels: 0.13

#4270 docs: update actions guide
  docs/using-garden/README.md
  docs/using-garden/actions.md
Labels: 0.13

#4365 chore: update remote sources example
  examples/remote-sources/garden.yml
  examples/remote-sources/worker/garden.yml
Labels: 0.13

#4163 docs: add sync mode detection example to migration guide
  docs/tutorials/migrating-to-bonsai.md
Labels: 0.13

#4388 fix: re-init the analytics handler metadata on project switch
  core/src/analytics/analytics.ts
  core/src/commands/base.ts
  core/src/commands/dev.tsx
  core/src/commands/serve.ts
  core/test/unit/src/analytics/analytics.ts
Labels: 0.13

#4415 perf(dev): add internal command for getting sync and deploy statuses
  core/src/commands/sync/sync-status.ts
  core/src/server/commands.ts
  core/src/server/instance-manager.ts
Labels: 0.13

#4379 docs: update and align README
  README.md
Labels: docs, 0.13, getting-started

#4491 Update helm version from `3.7.2` to `3.12.0`
  core/src/plugins/kubernetes/helm/helm-cli.ts
Labels: backport-to-0.12
