Repository garden-io/garden, pull requests merged in 2025-04, with the labels that each got.

#7060 docs: fix anchor links and typos in deprecations guide
  core/src/util/deprecations.ts
  docs/guides/deprecations.md
Labels: 0.13

#7061 fix(sync): await monitors stop on `sync stop` completion
  core/src/commands/sync/sync-stop.ts
Labels: 0.13

#7086 fix(git): replace vulnerable parse-git-config with ini file parser
  core/package.json
  core/src/vcs/git-sub-tree.ts
  package-lock.json
Labels: security

#7094 fix(git): replace vulnerable parse-git-config with ini file parser
  core/package.json
  core/src/vcs/git-sub-tree.ts
  package-lock.json
Labels: 0.13

#7115 chore: fix class name in homebrew formula template for 0.13
  support/homebrew-formula.rb.j2
Labels: 0.13

#7117 chore(deps): update `otel` dependencies to the latest versions
  core/package.json
  package-lock.json
Labels: 0.13

#7118 chore(support): update AWS and Azure cli libs in Docker images
  support/alpine.Dockerfile
  support/debian.Dockerfile
Labels: 0.13

#7120 tool(kubectl): update version to 1.32.3
  core/src/plugins/kubernetes/kubectl.ts
Labels: 0.13

#7119 tool(helm): update version to 3.17.2
  core/src/plugins/kubernetes/helm/helm-cli.ts
  docs/reference/action-types/Deploy/helm.md
  docs/reference/module-types/helm.md
Labels: 0.13

#7121 ci(integ): update kind from 1.29.8 to 1.32.3
  .circleci/config.yml
Labels: 0.13

#7161 tool(mutagen): update mutagen to 0.18.1 and base alpine image to 3.21.3
  core/src/mutagen.ts
  core/src/plugins/kubernetes/constants.ts
  images/k8s-sync/Dockerfile
  images/k8s-sync/garden.yml
  images/k8s-util/garden.yml
Labels: 0.13

#7029 fix(module-k8s): fix `deploymentImageId` in module conversion
  core/src/plugins/container/container.ts
  core/test/integ/src/plugins/kubernetes/container/deployment.ts
Labels: 0.13

#7168 fix(container): always respect env vars to control remote builder
  core/src/plugins/container/cloudbuilder.ts
  core/src/plugins/container/container.ts
  docs/reference/providers/container.md
Labels: 0.13

#7174 chore: fix `deprecated` and `internal` flags propagation in reference docs
  core/src/config/common.ts
  core/src/config/template-contexts/project.ts
  core/src/docs/common.ts
  core/src/docs/joi-schema.ts
  docs/reference/action-types/Deploy/container.md
  docs/reference/action-types/Deploy/helm.md
  docs/reference/action-types/Deploy/kubernetes.md
  docs/reference/commands.md
  docs/reference/module-types/container.md
  docs/reference/module-types/helm.md
  docs/reference/module-types/jib-container.md
  docs/reference/module-types/kubernetes.md
  docs/reference/providers/container.md
  docs/reference/template-strings/action-all-fields.md
  docs/reference/template-strings/action-specs.md
  docs/reference/template-strings/environments.md
  docs/reference/template-strings/modules.md
  docs/reference/template-strings/project-outputs.md
  docs/reference/template-strings/projects.md
  docs/reference/template-strings/providers.md
  docs/reference/template-strings/remote-sources.md
  docs/reference/template-strings/workflows.md
  docs/reference/workflow-config.md
Labels: 0.13

#6577 fix(solver): throw if a dependency failed and `throwOnError` is true
  core/src/garden.ts
  core/src/graph/solver.ts
  core/src/util/profiling.ts
  core/test/integ/src/plugins/kubernetes/container/build/build.ts
  core/test/unit/src/graph/solver.ts
  core/test/unit/src/tasks/resolve-action.ts
Labels: back-port-to-0.13

#7175 fix(solver): throw if a dependency failed and `throwOnError` is true
  core/src/garden.ts
  core/src/graph/solver.ts
  core/test/integ/src/plugins/kubernetes/container/build/build.ts
  core/test/integ/src/plugins/kubernetes/helm/deployment.ts
  core/test/unit/src/graph/solver.ts
  core/test/unit/src/tasks/resolve-action.ts
Labels: 0.13

#7176 fix: prevent unnecessary execution of builds referenced in runtime actions
  core/src/graph/actions.ts
  core/test/unit/src/actions/action-configs-to-graph.ts
  core/test/unit/src/graph/actions.ts
Labels: 0.13

#7173 docs: update the notice on the modules deprecation
  core/src/docs/generate.ts
  docs/reference/module-types/README.md
Labels: 0.13

#7177 fix: do not throw on unknown action types for disabled actions
  core/src/graph/actions.ts
  core/test/data/test-projects/disabled-action-without-provider/garden.yml
  core/test/unit/src/garden.ts
Labels: 0.13

#7181 ci: restore filtering config in 0.13 branch
  .circleci/config.yml
  .circleci/continue-config.yml
Labels: 0.13

#7180 chore: disable npm package publishing in release pipeline
  .github/workflows/publish-release.yml
Labels: back-port-to-0.13

#7185 chore: disable npm package publishing in release pipeline
  .github/workflows/publish-release.yml
Labels: 0.13
